steps:
# Step 1: Update Git submodules
- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    git submodule update --init --recursive
  env:
  - 'GIT_DEPTH=1000'

# Step 2: Build Docker image
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    LATEST_IMG_OPT=""
    PRETTY_BRANCH_NAME=$(echo "$BRANCH_NAME" | tr '/' '_')
    if [[ -n "$TAG_NAME" ]]; then
      PRETTY_BRANCH_NAME=$TAG_NAME
      LATEST_TAG=$(git tag --list '7.*' --sort=-v:refname | head -n1)
      if [[ "$TAG_NAME" == "$(printf "$TAG_NAME\n$LATEST_TAG" | tail -n1)" ]]; then
        echo "The new tag is the latest -> build image with latest tag."
        LATEST_IMG_OPT="-t europe-west1-docker.pkg.dev/tactile-acrobat-461712-m0/greengage-repo/gpdb7_u22:latest"
      fi
    elif [[ "$_EVENT_TYPE" == "pull_request" ]]; then
      SHA_IMG_OPT="-t europe-west1-docker.pkg.dev/tactile-acrobat-461712-m0/greengage-repo/gpdb7_u22:$SHORT_SHA"
    fi
    docker build -f ci/Dockerfile.ubuntu \
      -t europe-west1-docker.pkg.dev/tactile-acrobat-461712-m0/greengage-repo/gpdb7_u22:$PRETTY_BRANCH_NAME \
      $LATEST_IMG_OPT $SHA_IMG_OPT .
  env:
  - 'BRANCH_NAME=$BRANCH_NAME'
  - 'TAG_NAME=$TAG_NAME'
  - 'SHORT_SHA=$SHORT_SHA'
  - '_EVENT_TYPE=$EVENT_TYPE'

# Step 3: Push Docker images
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    PRETTY_BRANCH_NAME=$(echo "$BRANCH_NAME" | tr '/' '_')
    if [[ -n "$TAG_NAME" ]]; then
      PRETTY_BRANCH_NAME=$TAG_NAME
    fi
    docker push europe-west1-docker.pkg.dev/tactile-acrobat-461712-m0/greengage-repo/gpdb7_u22:$PRETTY_BRANCH_NAME
    if [[ -n "$TAG_NAME" ]]; then
      LATEST_TAG=$(git tag --list '7.*' --sort=-v:refname | head -n1)
      if [[ "$TAG_NAME" == "$(printf "$TAG_NAME\n$LATEST_TAG" | tail -n1)" ]]; then
         docker push europe-west1-docker.pkg.dev/tactile-acrobat-461712-m0/greengage-repo/gpdb7_u22:latest
      fi
    fi
    if [[ "$_EVENT_TYPE" == "pull_request" ]]; then
      docker push europe-west1-docker.pkg.dev/tactile-acrobat-461712-m0/greengage-repo/gpdb7_u22:$SHORT_SHA
    fi
  env:
  - 'BRANCH_NAME=$BRANCH_NAME'
  - 'TAG_NAME=$TAG_NAME'
  - 'SHORT_SHA=$SHORT_SHA'
  - '_EVENT_TYPE=$EVENT_TYPE'

images:
- 'europe-west1-docker.pkg.dev/tactile-acrobat-461712-m0/greengage-repo/gpdb7_u22'

options:
  logging: CLOUD_LOGGING_ONLY
