substitutions:
  _IMAGE_VERSION: "7"  # Default
steps:
# Step 1: Authenticate with Google Cloud
- name: 'gcr.io/cloud-builders/gcloud'
  id: 'auth'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    echo $${_GOCLOUD_AUTH_CREDS} > /tmp/creds.json
    gcloud auth activate-service-account --key-file=/tmp/creds.json
  secretEnv:
  - '_GOCLOUD_AUTH_CREDS'

# Step 2: Update Git submodules
- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    git submodule update --init --recursive
  env:
  - 'GIT_DEPTH=1000'

# Step 3: Build Docker image
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    LATEST_IMG_OPT=""
    SHA_TAG=""
    PRETTY_BRANCH_NAME=$(echo "$BRANCH_NAME" | tr '/' '_')
    if [[ -n "$TAG_NAME" ]]; then
      PRETTY_BRANCH_NAME=$TAG_NAME
      LATEST_TAG=$(git tag --list "${_IMAGE_VERSION}.*" --sort=-v:refname | head -n1)
      if [[ "$TAG_NAME" == "$(printf "$TAG_NAME\n$LATEST_TAG" | tail -n1)" ]]; then
        echo "Latest tag detected, building with latest tag."
        LATEST_IMG_OPT="-t europe-west4-docker.pkg.dev/tactile-acrobat-461712-m0/greengage/gpdb${_IMAGE_VERSION}_u22:latest"
      fi
    elif [[ "$_EVENT_TYPE" == "pull_request" ]]; then
      SHA_TAG="-sha-$SHORT_SHA"
    fi
    docker build -f ci/Dockerfile.ubuntu \
      -t europe-west4-docker.pkg.dev/tactile-acrobat-461712-m0/greengage/gpdb${_IMAGE_VERSION}_u22:$PRETTY_BRANCH_NAME$SHA_TAG \
      $LATEST_IMG_OPT .
  env:
  - 'BRANCH_NAME=$BRANCH_NAME'
  - 'TAG_NAME=$TAG_NAME'
  - 'SHORT_SHA=$SHORT_SHA'
  - '_EVENT_TYPE=$EVENT_TYPE'

# Step 4: Push Docker images
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    PRETTY_BRANCH_NAME=$(echo "$BRANCH_NAME" | tr '/' '_')
    if [[ -n "$TAG_NAME" ]]; then
      PRETTY_BRANCH_NAME=$TAG_NAME
    fi
    docker push europe-west4-docker.pkg.dev/tactile-acrobat-461712-m0/greengage/gpdb${_IMAGE_VERSION}_u22:$PRETTY_BRANCH_NAME
    if [[ -n "$TAG_NAME" ]]; then
      LATEST_TAG=$(git tag --list "${_IMAGE_VERSION}.*" --sort=-v:refname | head -n1)
      if [[ "$TAG_NAME" == "$(printf "$TAG_NAME\n$LATEST_TAG" | tail -n1)" ]]; then
        docker push europe-west4-docker.pkg.dev/tactile-acrobat-461712-m0/greengage/gpdb${_IMAGE_VERSION}_u22:latest
      fi
    fi
    if [[ "$_EVENT_TYPE" == "pull_request" ]]; then
      docker push europe-west4-docker.pkg.dev/tactile-acrobat-461712-m0/greengage/gpdb${_IMAGE_VERSION}_u22:$PRETTY_BRANCH_NAME$SHA_TAG
    fi
  env:
  - 'BRANCH_NAME=$BRANCH_NAME'
  - 'TAG_NAME=$TAG_NAME'
  - 'SHORT_SHA=$SHORT_SHA'
  - '_EVENT_TYPE=$EVENT_TYPE'

images:
- 'europe-west4-docker.pkg.dev/tactile-acrobat-461712-m0/greengage/gpdb${_IMAGE_VERSION}_u22'

options:
  logging: CLOUD_LOGGING_ONLY
