x-common-service: &common-service
  image: "${IMAGE}"
  privileged: true
  sysctls:
    kernel.sem: 500 1024000 200 4096
  init: true
  ulimits:
    nofile: 65535
  entrypoint: >
    sleep infinity

x-common-volumes: &common-volumes
  volumes:
    - ./ssh_keys/id_rsa:/home/gpadmin/.ssh/id_rsa
    - ./ssh_keys/id_rsa.pub:/home/gpadmin/.ssh/id_rsa.pub
    - ./sqldump/dump.sql:/home/gpadmin/gpdb_src/sqldump/dump.sql

services:
  cdw:
    <<: [*common-service, *common-volumes]
    working_dir: /home/gpadmin
    hostname: cdw
    volumes:
      - ./allure-results:/tmp/allure-results
      - ./logs_cdw:/logs

  sdw1:
    <<: [*common-service, *common-volumes]
    hostname: sdw1
    volumes:
      - ./logs_sdw1:/logs

  sdw2:
    <<: [*common-service, *common-volumes]
    hostname: sdw2
      - ./logs_sdw2:/logs

  sdw3:
    <<: [*common-service, *common-volumes]
    hostname: sdw3
      - ./logs_sdw3:/logs
  