FROM ubuntu:22.04 AS base

SHELL ["/bin/bash", "-o", "pipefail", "-c"]
WORKDIR /home/gpadmin

COPY README.Ubuntu.bash ./

RUN set -eux; \
    ./README.Ubuntu.bash; \
    rm -rf /var/lib/apt/lists/*; \
    rm README.Ubuntu.bash; \
# The en_US.UTF-8 locale is needed to run GPDB
    locale-gen en_US.UTF-8; \
# To run sshd directly, but not using `/etc/init.d/ssh start`
    mkdir /run/sshd; \
# Alter precedence in favor of IPv4 during resolving
    echo 'precedence ::ffff:0:0/96  100' >> /etc/gai.conf; \
# Install allure-behave for behave tests
    pip3 install --no-cache-dir --prefer-binary \
      allure-behave==2.4.0 \
      behave~=1.2.6 \
      coverage~=4.5 \
      gsutil \
      'mock<=5.0.0' \
      protobuf==3.20.0 \
      pytest

FROM base AS build

COPY . gpdb_src

RUN mkdir bin_gpdb

ENV TARGET_OS_VERSION=22 \
    TARGET_OS=ubuntu \
    OUTPUT_ARTIFACT_DIR=bin_gpdb \
    SKIP_UNITTESTS= \
# To set default locale for unittests
    LANG=en_US.UTF-8 \
    CONFIGURE_FLAGS="--enable-debug-extensions --with-gssapi --enable-cassert --enable-debug --enable-depend"

# Compile with running mocking tests
RUN gpdb_src/concourse/scripts/compile_gpdb.bash

FROM base AS code
COPY . gpdb_src
RUN rm -rf gpdb_src/.git/

FROM base AS test
COPY --from=code /home/gpadmin/gpdb_src gpdb_src
COPY --from=build /home/gpadmin/bin_gpdb /home/gpadmin/bin_gpdb
COPY --from=build /home/gpadmin/gpdb_src/VERSION gpdb_src
