name: Build for All Branches

on:
  push:
    branches:
      - '7.x'
    tags:
      - '7.*'

jobs:
  build-v7-rockylinux8:
    uses: magf/ci/.github/workflows/greengage-reusable-build.yml@main
    with:
      version: 7
      target_os: rockylinux
      target_os_version: 8
      python3: ''
    secrets:
      ghcr_token: ${{ secrets.GITHUB_TOKEN }}

  build-v6-ubuntu22:
    uses: magf/ci/.github/workflows/greengage-reusable-build.yml@main
    with:
      version: 7
      target_os: ubuntu
      target_os_version: 22
      python3: PYTHON3
    secrets:
      ghcr_token: ${{ secrets.GITHUB_TOKEN }}
