name: Build for All Branches

on:
  push:
    branches:
      - 'main'
    tags:
      - '6.*'

jobs:
  build-v6-centos7:
    if: startsWith(github.ref, 'refs/heads/v6') || startsWith(github.ref, 'refs/heads/feature/v6') || startsWith(github.ref, 'refs/tags/6.')
    uses: magf/ci/.github/workflows/greengage-reusable-build.yml@main
    with:
      version: 6
      target_os: centos
      target_os_version: 7
      python3: ''
    secrets:
      ghcr_token: ${{ secrets.GITHUB_TOKEN }}

  build-v6-ubuntu22:
    if: startsWith(github.ref, 'refs/heads/v6') || startsWith(github.ref, 'refs/heads/feature/v6') || startsWith(github.ref, 'refs/tags/6.')
    uses: magf/ci/.github/workflows/greengage-reusable-build.yml@main
    with:
      version: 6
      target_os: ubuntu
      target_os_version: 22
      python3: PYTHON3
    secrets:
      ghcr_token: ${{ secrets.GITHUB_TOKEN }}
