name: Build 6.x

on:
  push:
    tags: ['6.*']
  pull_request:
    branches: ['*']
    tags: ['6.*']
  workflow_dispatch:
    inputs:
      target_branch:
        description: 'Target branch for build'
        required: true
        default: 'main'
        type: choice
        options:
          - 6.x
          - main
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
      debug_mode:
        description: 'Enable debug mode'
        type: boolean
        default: false

jobs:
  build-v6-centos7:
    uses: magf/greengage-ci/.github/workflows/greengage-reusable-build.yml@main
    with:
      version: 6
      target_os: centos
      target_os_version: 7
      python3: ''
    secrets:
      ghcr_token: ${{ secrets.GITHUB_TOKEN }}

  build-v6-ubuntu22:
    uses: magf/greengage-ci/.github/workflows/greengage-reusable-build.yml@main
    with:
      version: 6
      target_os: ubuntu
      target_os_version: 22
      python3: python3
    secrets:
      ghcr_token: ${{ secrets.GITHUB_TOKEN }}
