name: Build 7.x

on:
  push:
    tags: ['7.*']
  pull_request:
    branches: ['*']
    tags: ['7.*']
  workflow_dispatch:
    inputs:
      target_branch:
        description: 'Target branch for build'
        required: true
        default: '7.x'
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
      debug_mode:
        description: 'Enable debug mode'
        type: boolean
        default: false

jobs:
  build-v7-rockylinux8:
    uses: magf/greengage-ci/.github/workflows/greengage-reusable-build.yml@main
    with:
      version: 7
      target_os: rockylinux
      target_os_version: 8
      python3: ''
    secrets:
      ghcr_token: ${{ secrets.GITHUB_TOKEN }}

  build-v7-ubuntu22:
    uses: magf/greengage-ci/.github/workflows/greengage-reusable-build.yml@main
    with:
      version: 7
      target_os: ubuntu
      target_os_version: 22
      python3: ''
    secrets:
      ghcr_token: ${{ secrets.GITHUB_TOKEN }}
