name: Build main Branch 6.x

on:
  push:
    branches:
      - 'main'
    tags:
      - '6.*'

jobs:
  build-v6-centos7:
    uses: magf/greengage-ci/.github/workflows/greengage-reusable-build.yml@main
    with:
      version: 6
      target_os: centos
      target_os_version: 7
      python3: ''
    secrets:
      ghcr_token: ${{ secrets.GITHUB_TOKEN }}

  build-v6-ubuntu22:
    uses: magf/greengage-ci/.github/workflows/greengage-reusable-build.yml@main
    with:
      version: 6
      target_os: ubuntu
      target_os_version: 22
      python3: PYTHON3
    secrets:
      ghcr_token: ${{ secrets.GITHUB_TOKEN }}
